# this is a verysimple standard config
[[listen]]
protocol = "socks5"
host = "127.0.0.1"
port = 10800
tag = "my_socks51"


[[dial]]
tag = "my_vlesss1"
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "127.0.0.1"
port = 4433
version = 0
insecure = true
utls = true



[route]
mycountry = "CN"
