# this is a verysimple standard config
[[listen]]
protocol = "socks5"
host = "127.0.0.1"
port = 10800
tag = "my_socks51"


[[dial]]
tag = "my_vlesss1"
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "127.0.0.1"
port = 4433
version = 0
insecure = true
utls = true


# route这一项是可选的,如果没给出的话,就不分流;写了mycountry后, 向该国家的ip发送的请求就会直连, 然后其他的过代理
# mycountry的字母必须是两个，而且必须大写。这个也会自动被用于顶级域名的国别分流
# 同时，必须要一个 GeoLite2-Country.mmdb 文件 放在verysimple的相同目录下. 详情见 README.md
[route]
mycountry = "CN"
