# this is a verysimple standard config
[[listen]]
tag = "my_vlesss1"
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "127.0.0.1"
port = 4433
version = 0
insecure = true
fallback = ":80"
cert = "cert.pem"
key = "cert.key"

[[dial]]
protocol = "direct"


[[fallback]]
path = "/asf"
dest = 6060

