# this is a verysimple standard config
[[listen]]
tag = "my_vlesss1"
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "127.0.0.1"
port = 4433
version = 0
insecure = true
fallback = ":80"
cert = "cert.pem"
key = "cert.key"

[[dial]]
protocol = "direct"

# fallback这一项是可选的，如果没有的话，或者未匹配，则默认使用listen提供的fallback
# 如果listen也没提供fallback，那就会直接断开连接
[[fallback]]
path = "/asf"
dest = 6060

