# this is a verysimple standard server config
[[listen]]
tag = "my_vlesss1"
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "0.0.0.0"
port = 4433
version = 0
insecure = true
fallback = ":80"    #默认回落地址.必须是本机ip
cert = "cert.pem"   # 这里既可以默认放在程序本身目录下，也可以指定完整路径
key = "cert.key"

[[dial]]
protocol = "direct"

# fallback这一项是可选的，如果没有的话，或者未匹配，则默认使用listen提供的fallback
# 如果listen也没提供fallback，那就会直接断开连接
[[fallback]]
path = "/asf"
dest = 6060

[app]

# 日志等级, 0=debug, 1=info, 2=warning, 3=error,4=fatal, 推荐测试时使用1, 服务端使用2或3
loglevel = 1

