[[listen]]
protocol = "socks5"
host = "127.0.0.1"
port = 10800

[[dial]]
protocol = "trojans"    
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"   
ip = "127.0.0.1"
host = "your-domain-name.com"  
port = 4434
insecure = true
utls = true
use_mux = true  # 只需要客户端指明使用mux即可, 服务端自动适配.

