[[listen]]
tag = "my_socks5"  
protocol = "socks5"
host = "127.0.0.1" 
port = 10800       

[[dial]]
tag = "my_vlesss1"   
protocol = "vlesss" 
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"   
host = "127.0.0.1"     
port = 4433      
version = 1
insecure = true  
utls = true
extra = { vless1_udp_multi = true } 

# 用 vless1_udp_multi 选项 开启vless v1的 分离信道传输udp功能. udp分离信道发送 性能会比默认的 多路复用 发送性能要高。
# 在有大量向不同 远程地址发送的 udp链接 存在时，才会体现出优势 , 比如一些 实时游戏 或者 多人视频会议。
# 分离信道 又可以叫 【多信道】，因此我们用 multi 来表示。
