[[listen]]
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "0.0.0.0"
port = 4434
version = 0
insecure = true
fallback = ":80"
cert = "cert.pem"
key = "cert.key"

# advancedLayer = "ws"


# 下面是 http伪装头的 配置
# 完全兼容v2ray, 可参考 https://www.v2fly.org/config/transport/tcp.html#httprequestobject


# content不需要给出, 因为一切都有默认值, 如果你要定制, 可以给出.
[listen.header.request]
version = "1.1"
method = "GET"
path = ["/very","/simple"]  # 每次请求随机选择一个值。

# headers里的数组, 每次请求随机选择一个值。 

# 如果使用 ws, 则 Connection头必须指明为 Upgrade
#headers.Connection = [  "Upgrade"   ]


#headers.Host = ["www.baidu.com","www.bing.com"]
#headers.User-Agent = [ "Mozilla/5.0 (my fake system)"]
#headers.Accept-Encoding = [ "gzip, deflate"  ]
#headers.Connection = [  "keep-alive"   ]
#headers.Pragma = ["no-cache"]

# 还可以配置 response, 道理一样。这里直接省略了,就是使用默认值, 参考 v2ray文档。

#[listen.header.response]
# 如果使用 ws, 则 Connection头必须指明为 Upgrade, response 也一样
#headers.Connection = [  "Upgrade"   ]


[[dial]]
protocol = "direct"
