# this is a verysimple standard client config
# toml 格式 要注意的是，字符串类型 必须用 引号括起来

[app]   # app 项是可选的

# 日志等级, 0=debug, 1=info, 2=warning, 3=error,4=fatal,默认为1. 
# 推荐测试时使用1, 服务端使用2或3; 显然日志越少越快, 设为4的话网速是最快的.
loglevel = 1

# 如果 default_uuid 给出了，且某个 需要uuid的地方没给出，则会使用 default_uuid 的值

# default_uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"

#mycountry = "CN" #全局级的 国别分流配置, 见下面route的注释

# noreadv = true    

# 也可以用命令行参数 -readv=false 来关闭 readv . readv开启 一般是会加速的, 
#  你可以在测速时开关一下readv看看测速的变化, 如果遇到了readv减速的话， 可以通过设置把它关闭。

[[listen]]
tag = "my_socks5"   # 可选, 但不可与其他tag重复
protocol = "socks5" # 必填
host = "127.0.0.1"  # 必填, 可填ip或域名；如果 network是unix的话，要填一个文件名(不需要已存在,可以是完整路径).
port = 10800        # 必填

[[dial]]
tag = "my_vlesss1"  # 同listen对应配置, 可选, 但不可与其他tag重复
protocol = "vlesss" # vless 的 尾缀s 表示 使用tls
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"   # 这个只是一个示例uuid,请自己生成一个新的.
host = "127.0.0.1"     # 同listen对应配置, 可填ip或域名；如果 network是unix的话，要填一个文件名(不需要已存在,可以是完整路径).
#network = "udp"   

# network 目前支持 tcp,udp 和unix;如果不给出则默认为 tcp; dial和listen都可配置此项
# network和用什么协议无关.比如我们可以硬把一个 ss协议的数据通过 unix socket来传输.
# 如果用udp的话，传输vless 时即可理解为 udp over udp 或者 tcp over udp, 底层用udp来传输tcp/udp的承载数据.
# 总之我们verysimple的理念就是 代理协议是什么协议 与 网络层使用什么协议是无关的

# ip = "127.0.0.1" 

# 除了host之外，也可使用 ip = "127.0.0.1"; 一般用了host就不需要再写ip, 
# 但是如果用了cdn 的话, 就要单独提供 ip 和 host
#  单独提供 ip 的好处就是不用解析域名了

# tls = true    

# 除了在 protocol 字段使用 s尾缀 之外，还可以明示使用tls. 
# 这两种方法不可重复使用.我们首选前者, 更简约, 当然如果你使用时，需要频繁开关tls，那么可以单独列出来 便于配置

port = 4433     # 必填
version = 0     # 协议版本, 可省略, 省略则默认为最老版本
insecure = true # 我们示例使用自签名证书，所以要开启 insecure. 实际场合请使用真证书并关闭 insecure
utls = true     #是否使用 utls 来应用 chrome指纹进行伪装

# alpn=["http/1.1"]     # 在开启tls时有效，如果服务端和客户端都配置了alpn，则 服务端和客户端 必须都有相同的alpn项才能建立tls连接

# 如果要使用 websocket/grpc ，则 客户端和服务端 都要配置 advancedLayer 和 path

# advancedLayer = "ws"  # 也可为grpc
# path = "/ohmygod_verysimple_is_very_simple" #为了防探测这里越长越随机越好


# route 是在我们代理界是分流的意思。 这一项是可选的,如果没给出的话,就不分流;
# 写了 country 后, 向该国家的ip发送的请求就会直连, 然后其他的过代理
# country的字母必须是两个，而且必须大写。这个也会自动被用于顶级域名的国别分流
# 同时，必须要一个 GeoLite2-Country.mmdb 文件 放在verysimple的相同目录下. 详情见 README.md

# 具体的其它详细 分流配置请参考 multi.client.toml 和 multi.server.toml 文件, 因为会涉及到多个dial

[[route]]
country = ["CN"]
dialTag = "direct"