# this is a verysimple standard server config
[[listen]]
tag = "my_vlesss1"
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "0.0.0.0"
port = 4433
version = 0
insecure = true
fallback = ":80"    # 默认回落地址.ip必须是本机ip(可以省略ip而只写端口,程序会默认补全127.0.0.1), 或者unix domain socket的文件名/路径, 或者 udp://127.0.0.1:80 这种url格式。 （用udp以试图回落到 nginx的 无tls 的 http3 服务端口）

cert = "cert.pem"   # 这里既可以默认放在程序本身目录下，也可以指定完整路径
key = "cert.key"

[[dial]]
protocol = "direct"
# fullcone = true   # 默认的fullcone是关闭状态, 可以取消注释以打开. 不过vless v0的话没用，因为vless v0不支持fullcone。 v1或者trojan可以打开 该选项.

# fallback这一项是可选的，如果没有的话，或者未匹配，则默认使用listen提供的fallback
# 如果listen也没提供fallback，那就会直接断开连接
[[fallback]]
path = "/asf"   # 按path 匹配此 回落
dest = 6060     # 回落到本机端口 6060

# dest = "127.0.0.1:8080"  # dest 还可以用这种格式
# dest = "/path/to/your/unix_domain_socket"    # 还可以用 unix domain socket 的文件名,可以绝对路径或者相对路径

# 还可以按sni和 alpn匹配（tls里的host和 alpn）

# sni = "your.domain.com"
# alpn = ["h2","http/1.1"]

# 一个fallback中 可以多个条件同时匹配，此时只有完全匹配所有条件 才算匹配 此fallback

# 另外，sni和alpn的 匹配 只在 我们listen配置使用了 tls时才会有效，比如如果nginx前置的话，那么我们就是无法匹配这两项的.