[[listen]]
protocol = "socks5"
host = "127.0.0.1"
port = 10800


[[dial]]
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "127.0.0.1"
port = 4434
version = 0
insecure = true
utls = true
# advancedLayer = "ws"  # ws也可应用我们的http header

[dial.header.request]
version = "1.1"
method = "GET"
path = ["/very","/simple"]  # 每次请求随机选择一个值。

# 如果使用 ws, 则 Connection头必须指明为 Upgrade
#headers.Connection = [  "Upgrade"   ]

#[dial.header.response]
# 如果使用 ws, 则 Connection头必须指明为 Upgrade, response 也一样
#headers.Connection = [  "Upgrade"   ]
