name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - ".github/workflows/*.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - ".github/workflows/*.yml"

jobs:
  test:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
          check-latest: true
      - name: Checkout codebase
        uses: actions/checkout@v3

       - name: Test
        run: go test -timeout 1h -v ./...